### ISSUE TITLE
Swipe image out of screen to go back, where image orientation is dynamic

### ISSUE THREAD

**Issue by warnaars** [aFrogleap/SimpleImageViewer#1]
### Expected behavior
When dragging an image from detail view the image can rotate (like in the Tweetbot iOS application)
When swiping the image out of the screen, the user returns to the previous screen (image overview)
When letting the image go, it restores to the image detail screen, with the correct orientation and the image centred in the screen.

### Actual behavior
Image in detail view can be dragged but will stay oriented in the same orientation

### Steps to reproduce the behavior
Check example in Tweetbot iOS application

**Comment by LcTwisk** [comment]
Hi @warnaars, thanks for the feature request. We will look into this and see what is possible!

**Comment by LcTwisk** [comment]
Supporting different animations is not our focus at the moment. We would like to keep the project as simple as possible. Will close this for now!
