### ISSUE TITLE
iPhoneX8 goes down a few pixels down.

### ISSUE THREAD

**Issue by eastswift** [aFrogleap/SimpleImageViewer#12]
IPhone 8 goes down a few pixels down.
Other devices have no problem.

It seems to be a problem of iPhone X's height, but I do not know the solution.

**Comment by LcTwisk** [comment]
Thanks for reporting. Let’s see if I can reproduce the issue 👍🏼

**Comment by LcTwisk** [comment]
@eastswift can you check if the issue is fixed in the latest version (1.1.1)?

**Comment by eastswift** [comment]
It works well. It's cool.
