### ISSUE TITLE
graphic issue on iPhone X

### ISSUE THREAD

**Issue by alessunder** [aFrogleap/SimpleImageViewer#14]
### Expected behavior
Should have a linear animation when opening on iPhone X.

### Actual behavior
After the end of the animation the image has a jerky effect

### Steps to reproduce the behavior
Open any image with iPhone X

**Comment by LcTwisk** [comment]
Can you double check if you are on version `1.1.1`? This sounds like a problem that should already be fixed in the latest version.

**Comment by LcTwisk** [comment]
I’m closing this until more information is provided
