### ISSUE TITLE
Could not load the "closeButton" image referenced from a nib in the bundle with identifier "org.cocoapods.SimpleImageViewer"

### ISSUE THREAD

**Issue by eastswift** [aFrogleap/SimpleImageViewer#3]
I just installed simpleViewer as a pod. And I have confirmed that there is no closeButton image file. So I added a closebutoon file to my asset. I still get that message. Why? 

Thank you for your great open source.

**Comment by LcTwisk** [comment]
It looks like we forgot to add the resources to the Cocoapods configuration. I will take a look at it to see what I can do.

Thanks for reporting the issue!

**Comment by LcTwisk** [comment]
By the way, you can use the library by installing it through Carthage in the meantime!

**Comment by LcTwisk** [comment]
This should be fixed in version 1.0.1:
Please run:
```ruby
pod repo update
```
then
```ruby
pod 'SimpleImageViewer', '~> 1.0.1'
```
and you should be good to go!
Please let me know if it works so we can close this issue.

**Comment by eastswift** [comment]
I just updated the pod. The message no longer appears. It is wonderful.
