### ISSUE TITLE
ImageBlock

### ISSUE THREAD

**Issue by hbhasin1** [aFrogleap/SimpleImageViewer#30]
when i click on an image at a particular index in collection view that moment i want to download a high resolution image and pass that image in the imageviewer.

unitl the image downloads the screen gets stuck and doesn't present the image controller

**Comment by eelcokoelewijn-afrogleap** [comment]
Hi @hbhasin1,

Could you provide us with a code sample of what you exactly are trying todo? The first thing which pops to my mind is that you do the download of the high-res image on the main- thread which blocks the UI before animating further.
Could you check if you are downloading on the main thread, instead of a background thread?

**Comment by hbhasin1** [comment]
func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
            
            let configuration = ImageViewerConfiguration { config in
                if let url: String = self.cloneProductListDataObj?.images[indexPath.row].largeResolutionImgSrc {
                    let urlStr: String = url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
                    if let searchURL = URL(string: urlStr) {
                        if let imageData : Data = try? Data(contentsOf: searchURL) {

                            config.image = UIImage(data: imageData, scale: 1.0)
                        }
                    }
                }
            }
            present(ImageViewerController(configuration: configuration), animated: true)
        }

This is what i am doing on collection view didSelect method

**Comment by eelcokoelewijn-afrogleap** [comment]
Yes, so as I was mentioning before. You are doing the download on the main-thread, this blocks the UI from performing the transition- animation. 
Ideally you have the image already downloaded or set the image after it's downloaded in the background.
@LcTwisk Any ideas how to keep a nice transition from the gallery to the imageviewer and replace the original image with the downloaded version?

**Comment by LcTwisk** [comment]
Hi @eelcokoelewijn-afrogleap!
That's where the `imageBlock` prop is for:

`        let configuration = ImageViewConfiguration { config in
            config.imageBlock = { block in
                if let url = self.cloneProductListDataObj?.images[indexPath.row].largeResolutionImgSrc,
                    let urlStr = url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
                    let searchURL = URL(string: urlStr) {
                    URLSession.shared.dataTask(with: url) { data, response, error in
                        guard let data = data, let image = UIImage(data: data) else { return }
                        DispatchQueue.main.async() {
                            block(image)
                        }
                    }
                }
            }
        }
        present(ImageViewerController(configuration: configuration), animated: true)`

**Comment by eelcokoelewijn-afrogleap** [comment]
@hbhasin1 Can you check if the purposed solution by @LcTwisk ☝️ and see if your issue is resolved?

**Comment by hbhasin1** [comment]
let configuration = ImageViewerConfiguration { config in
                    config.imageBlock = { block in
                        if let url = self.cloneProductListDataObj?.images[indexPath.row].largeResolutionImgSrc, let urlStr = url.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed), let searchURL = URL(string: urlStr) {
                            URLSession.shared.dataTask(with: searchURL) { data, response, error in guard let data = data, let image = UIImage(data: data) else { return }
                                self.cloneProductListDataObj?.images[indexPath.row].imgData = data
                                DispatchQueue.main.async {
                                    block(image)
                                }
                            }
                        }
                    }
                }
                self.present(ImageViewerController(configuration: configuration), animated: true)

Did same exactly but didn't work

**Comment by eelcokoelewijn-afrogleap** [comment]
@hbhasin1 Could you be a bit more specific on what didn't work? Do you still have the same behaviour, where the UI is stuck until the image is downloaded? If possible could you provide us with a sample project including the code you are using now?

**Comment by eelcokoelewijn-afrogleap** [comment]
@hbhasin1 Did the missing `resume()` fix-it?

**Comment by hbhasin1** [comment]
Yes that fixed the issue.
and is there any way to give background color to the image viewer?

Thanks
