### ISSUE TITLE
Causes application freeze (not crash)

### ISSUE THREAD

**Issue by sukov** [aFrogleap/SimpleImageViewer#6]
This video which is recorded on a device will show you the steps to reproduce the bug. The application I've used is your example project. The only change I made to the project is resizing the images to smaller resolution.

[simpleimageviewer_freeze_reproduce.zip](https://github.com/aFrogleap/SimpleImageViewer/files/1373656/simpleimageviewer_freeze_reproduce.zip)

**Comment by LcTwisk** [comment]
Hi @sukov! Thank you very much for creating this ticket. I'm able to reproduce your issue. I hope to find some free time in the coming days to fix it.
