### ISSUE TITLE
ImageViewController is not being deallocated

### ISSUE THREAD

**Issue by sukov** [aFrogleap/SimpleImageViewer#7]
I found out that transitionHandler in ImageViewController is keeping it from deallocating. I hope that you will investigate further.

**Comment by LcTwisk** [comment]
Thanks for reporting. This might be related to #6, will look at this as well.

**Comment by sukov** [comment]
I tried adding transitionHandler = nil in viewDidDissapear in ImageVC. That way ImageVC gets deallocated but the bug(app freeze) still appears. I hope this helps.

**Comment by LcTwisk** [comment]
@sukov I made a PR (#8) with fixes for #6 and #7, it would be nice if you could verify if fixes the problems for you as well.

**Comment by sukov** [comment]
It works perfect now, great job. I will close both issues, thanks for the fast response.

**Comment by LcTwisk** [comment]
Awesome! I've push a version with the fixes this weekend ;)
